version: '3.7'

services:
  database:
    container_name: database
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - application
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  backend:
    build: .
    env_file:
      - .env
    ports:
      - 3001:${APPLICATION_PORT}
    networks:
      - application
    depends_on:
      database:
        condition: service_healthy
        restart: true
    

networks:
  application:

volumes:
  postgres_data:
  redis_data: