version: '3.7'

services:
  database:
    container_name: database
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5433:5432
    networks:
      - application
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build: .
    env_file:
      - .env
    ports:
      - 3001:${APPLICATION_PORT}
    networks:
      - application
    

networks:
  application:

volumes:
  postgres_data:
  redis_data: